### ISSUE TITLE
Register error || "sha" wasn't supplied.

### ISSUE THREAD

**Issue by pxldevv** [wdhdev/is-a-dev-cli#1]
```
√ What subdomain would you like? ... 709
√ What type of record do you want to use? » MX
√ What should the value of the record be? ... mx1.improvmx.com

× UNHANDLED ERROR
× ERROR → Error
i REASON → HttpError: Invalid request.

"sha" wasn't supplied.
i ERROR STACK ↓
 Error: HttpError: Invalid request.

"sha" wasn't supplied.
    at C:\Users\student\AppData\Roaming\npm\node_modules\@is-a-dev\cli\src\functions\register.js:81:41
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


C:\Users\student>
```

**Comment by wdhdev** [comment]
I am very sorry for the very late response, I never saw this issue show up in my notifications 😬

This issue would be due to the domain JSON file already existing in your forked repository.
To fix this you should delete your fork and try re-registering.

**Comment by pxldevv** [comment]
I didn't have a forked repo though. I think the problem occured when I used numbers as the domain because it worked without the numbers.

Thanks!
