### ISSUE TITLE
Domain details not showing

### ISSUE THREAD

**Issue by ProxyJohnny** [wdhdev/is-a-dev-cli#3]
i recently registered johnny1337.is-a.dev  here is the commit details https://github.com/ProxyJohnny/register/commit/c23913f5b4c66f0a67669a95f055b3c66f1dd754 but it not showing on website

**Comment by wdhdev** [comment]
This is because the CLI uses the [is-a.dev Raw API](https://github.com/wdhdev/is-a-dev-cli) which is only updated every ~15 minutes.
